---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.userPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
...
