---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.service.extHttpsPort }}
      targetPort: {{ .Values.service.intHttpsPort }}
    - name: http
      port: {{ .Values.service.extHttpPort }}
      protocol: TCP
      targetPort: {{ .Values.service.intHttpPort }}
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
  selector:
    app: {{ .Chart.Name }}
...
