---
# SPDX-License-Identifier: AGPL-3.0-or-later
apiVersion: v2
name: sites-faciles
version: 0.0.1
description: A Helm chart for deploying french government website framwork 'sites-faciles' on an OpenShift like Kubernetes cluster
type: application
keywords:
  - sites-faciles
  - DSFR
  - python
  - Django 
  - Wagtail
  - postgresql
  - openshift
  - helm
home: https://github.com/hnoel/sites-faciles
sources:
  - https://github.com/numerique-gouv/sites-faciles
-dependencies:
 - name: postgresql
   version: 18.5.15
   repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: henri NOËL
    email: hnoel@users.noreply.github.com
icon: https://cdn.jsdelivr.net/npm/@gouvfr/dsfr@1.14.4/dist/favicon/favicon.svg
appVersion: "3.1.1"
deprecated: false
...
