---
{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "sceau.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "sceau.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "sceau.chart" . }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "sceau.fullname" . }}
  port:
    targetPort: http
  {{- if .Values.route.tls }}
  tls:
    termination: 'edge'
    insecureEdgeTerminationPolicy: 'Redirect'
  {{- end }}
{{- end }}
...
