---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "sceau.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "sceau.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "sceau.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sceau.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sceau.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      restartPolicy: Always

      containers:
        - name: httpd
          image: registry.access.redhat.com/hi/httpd:latest-builder
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.intHttpPort }}
              protocol: TCP

          volumeMounts:
            - name: httpd-conf
              mountPath: /etc/httpd/conf.d/zzz-php-fpm.conf
              subPath: zzz-php-fpm.conf

          resources:
            {{- toYaml .Values.httpd.resources | nindent 12 | default "" }}

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.intHttpPort }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.intHttpPort }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

        - name: php-fpm
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          volumeMounts:
            - name: php-fpm-conf
              mountPath: /etc/php-fpm.d/www.conf
              subPath: www.conf

          env:
            - name: SCEAU_TYPE_BD
              value: "mysql"
            - name: SCEAU_VERSION
              value: "debug"
            - name: SCEAU_DATE
              value: "01/01/1970"
            - name: SCEAU_HOST
              value: "{{ .Values.mariadb.primary.service.name }}-{{ .Values.mariadb.primary.service.ports.mysql }}.{{ .Values.namespace }}.svc.cluster.local"

            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}

            {{- with .Values.secret }}
            - name: SCEAU_BASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: MARIADB_DATABASE
            - name: SCEAU_BASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: MARIADB_USER
            - name: SCEAU_BASE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: MARIADB_PASSWORD
            {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 | default "" }}

  volumes:
    - name: httpd-conf
      configMap:
      name: {{ include "sceau.fullname" . }}-config
    - name: php-fpm-conf
      configMap:
      name: {{ include "sceau.fullname" . }}-config

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  revisionHistoryLimit: 0
  progressDeadlineSeconds: 600
...
