---
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "sceau.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "sceau.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "sceau.chart" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.extHttpPort }}
      targetPort: "{{ .Values.service.intHttpPort }}"
    - name: php
      protocol: TCP
      port: 9000
      targetPort:  "{{ .Values.service.intPhpPort }}"
  sessionAffinity: None
  ipFamilies:
    - "IPv4"
  ipFamilyPolicy: "SingleStack"
  internalTrafficPolicy: "Cluster"
  selector:
    app.kubernetes.io/name: {{ include "sceau.name" . }}
...
