---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sceau.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  zzz-php-fpm.conf: |
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so

    DocumentRoot "/var/www/html"

    <Directory "/var/www/html">
      Options FollowSymLinks
      AllowOverride All
      Require all granted
    </Directory>

    DirectoryIndex index.php index.html

    <FilesMatch "\.php$">
      SetHandler "proxy:fcgi://127.0.0.1:9000"
    </FilesMatch>

  www.conf: |
    ; Minimal override to force TCP listener on localhost only
    ; (keeps php-fpm running and limits exposure to the pod)
    listen = 127.0.0.1:9000
    ; Configuration for the default pool
    [www]
    ; Process manager
    pm = static
    ; Maximum number of child processes
    pm.max_children = 4444
...
