---
apiVersion: "v1"
kind: ConfigMap
metadata:
  name: {{ include "sceau.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "sceau.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  zzz-php-fpm.conf: |
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so

    DocumentRoot "/var/www/html"

    <Directory "/var/www/html">
      Options FollowSymLinks
      AllowOverride All
      Require all granted
    </Directory>

    DirectoryIndex index.php index.html

    ProxyPassMatch "^/(.*\.php)$" "fcgi://php.hnoel-dev.svc.cluster.local/src/$1"
    <FilesMatch "\.php$|status|ping|pong">
      SetHandler "proxy:fcgi://php.hnoel-dev.svc.cluster.local"
    </FilesMatch>
  www.conf: |
    ; Configuration for the default pool
    [www]
    user = apache
    group = apache
    ; Minimal override to force TCP listener on localhost only
    ; (keeps php-fpm running and limits exposure to the pod)
    listen = 0.0.0.0:9000
    listen.acl_users = apache,nginx
    ; Process manager
    pm = dynamic
    ; Maximum number of child processes
    pm.max_children = 50
    pm.start_servers = 5
    pm.min_spare_servers = 5
    pm.max_spare_servers = 35
    pm.status_path = /status
    ping.path = /ping
    ping.response = pong
    slowlog = /var/log/php-fpm/www-slow.log
    security.limit_extensions = .php .js .css .ico .gif .png
    php_admin_value[error_log] = /var/log/php-fpm/www-error.log
    php_admin_flag[log_errors] = on
    php_value[session.save_handler] = files
    php_value[session.save_path]    = /var/lib/php/session
...
