---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # Base64 encoded data
  password: cGFzc3dvcmQ= # "password" base64 encoded
stringData:
  # Raw data (automatically base64 encoded by Kubernetes)
  MARIADB_DATABASE: "appdb"
  MARIADB_USER: "appuser"
  MARIADB_PASSWORD: "change-me"
  MARIADB_ROOT_PASSWORD: "change-me-root"
...
