---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # Base64 encoded data
  password: cGFzc3dvcmQ= # "password" base64 encoded
stringData:
  # Raw data (automatically base64 encoded by Kubernetes)
  MARIADB_DATABASE: "appdb"
  MARIADB_USER: "appuser"
  mariadb-password: "change-me"
  mariadb-root-password: "change-me-root"
  mariadb-replication-password : "change-me-replication"
...
