---
replicaCount: 2

image:
  repository: ghcr.io/hnoel/demarche.numerique.gouv.fr
  tag: "main"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

route:
  enabled: true
  host: demarche.numerique.gouv.fr # à surcharger en prod
  tls: true

resources:
  limits:
    cpu: "2"
    memory: "2Gi"
  requests:
    cpu: "1"
    memory: "1Gi"

env:
  - name: DJANGO_SETTINGS_ENV
    value: "production"
  - name: ACTIVE_STORAGE_SERVICE
    value: "s3"
  - name: AGENT_CONNECT_ENABLED
    value: ""
  - name: AGENT_CONNECT_ID
    value: ""
  - name: AGENT_CONNECT_SECRET
    value: ""
  - name: AGENT_CONNECT_BASE_URL
    value: ""
  - name: AGENT_CONNECT_JWKS
    value: ""
  - name: AGENT_CONNECT_REDIRECT
    value: ""
  - name: API_ADRESSE_URL
    value: "https://api-adresse.data.gouv.fr"
  - name: API_COJO_URL
    value: ""
  - name: API_CPS_AUTH
    value: ""
  - name: API_CPS_CLIENT_ID
    value: ""
  - name: API_CPS_CLIENT_SECRET
    value: ""
  - name: API_CPS_PASSWORD
    value: ""
  - name: API_CPS_URL
    value: ""
  - name: API_CPS_USERNAME
    value: ""
  - name: API_EDUCATION_URL
    value: "https://data.education.gouv.fr/api/records/1.0"
  - name: API_ENTREPRISE_DEFAULT_SIRET
    value: ""
  - name: API_ENTREPRISE_KEY
    value: ""
  - name: API_ISPF_AUTH_URL
    value: ""
  - name: API_ISPF_URL
    value: ""
  - name: API_ADRESSE_URL
    value: "https://data.geopf.fr/geocodage"
  - name: API_ISPF_PASSWORD
    value: ""
  - name: API_ISPF_USER
    value: ""
  - name: APPLICATION_BASE_URL
    value: "https://www.mes-demarches.gov.pf"
  - name: APPLICATION_NAME
    value: "Mes-Démarches"
  - name: APP_HOST
    value: "localhost:3000"
  - name: APP_NAME
    value: "tps_local"
  - name: AR_ENCRYPTION_KEY_DERIVATION_SALT
    value: ""
  - name: AR_ENCRYPTION_PRIMARY_KEY
    value: ""
  - name: BASIC_AUTH_ENABLED
    value: "disabled"
  - name: BASIC_AUTH_PASSWORD
    value: ""
  - name: BASIC_AUTH_USERNAME
    value: ""
  - name: CARRIERWAVE_CACHE_DIR
    value: "$APP_PATH/tmp/carrierwave"
  - name: CLAMAV_ENABLED
    value: "disabled"
  - name: COJO_JWT_RSA_PRIVATE_KEY
    value: ""
  - name: CRISP_CLIENT_KEY
    value: ""
  - name: CRISP_ENABLED
    value: "disabled"
  - name: DB_DATABASE
    value: "tps"
  - name: DB_HOST
    value: "postgres"
  - name: DB_PASSWORD
    value: "tps_development"
  - name: DB_POOL
    value: ""
  - name: DB_USERNAME
    value: "tps_development"
  - name: DB_PORT
    value: "5432"
  - name: UNIVERSIGN_API_URL
    value: "https://ws.universign.eu/tsa/post/"
  - name: UNIVERSIGN_USERPWD
    value: ""
  - name: API_GEO_DEGRADED_MODE
    value: ""
  - name: API_GEO_URL
    value: "https://geo.api.gouv.fr"
  - name: DEMANDE_INSCRIPTION_ADMIN_PAGE_URL
    value: "https://www.mes-demarches.gov.pf/commencer/dmra-devenir-administrateur-de-demarches-en-ligne"
  - name: DOLIST_BALANCING_VALUE
    value: ""
  - name: DOLIST_USERNAME
    value: ""
  - name: DOLIST_PASSWORD
    value: ""
  - name: DOLIST_ACCOUNT_ID
    value: ""
  - name: DOLIST_API_KEY
    value: ""
  - name: DOC_URL
    value: "https://mes-demarches.gitbook.io/documentation"
  - name: DS_PROXY_URL
    value: ""
  - name: ENCRYPTION_SERVICE_SALT
    value: ""
  - name: FACEBOOK_CLIENT_ID
    value: ""
  - name: FACEBOOK_CLIENT_SECRET
    value: ""
  - name: FAVICON_16PX_SRC
    value: "favicons/pf16x16.png"
  - name: FAVICON_32PX_SRC
    value: "favicons/pf32x32.png"
  - name: FAVICON_96PX_SRC
    value: "favicons/pf96x96.png"
  - name: FC_PARTICULIER_BASE_URL
    value: ""
  - name: FC_PARTICULIER_ID
    value: ""
  - name: FC_PARTICULIER_SECRET
    value: ""
  - name: FOG_DIRECTORY
    value: ""
  - name: FOG_ENABLED
    value: ""
  - name: FOG_OPENSTACK_API_KEY
    value: ""
  - name: FOG_OPENSTACK_AUTH_URL
    value: ""
  - name: FOG_OPENSTACK_IDENTITY_API_VERSION
    value: ""
  - name: FOG_OPENSTACK_REGION
    value: ""
  - name: FOG_OPENSTACK_TENANT
    value: ""
  - name: FOG_OPENSTACK_URL
    value: ""
  - name: FOG_OPENSTACK_USERNAME
    value: ""
  - name: GITHUB_CLIENT_ID
    value: ""
  - name: GITHUB_CLIENT_SECRET
    value: ""
  - name: GOOGLE_CLIENT_ID
    value: ""
  - name: GOOGLE_CLIENT_SECRET
    value: ""
  - name: HELPSCOUT_CLIENT_ID
    value: ""
  - name: HELPSCOUT_CLIENT_SECRET
    value: ""
  - name: HELPSCOUT_MAILBOX_ID
    value: ""
  - name: HELPSCOUT_WEBHOOK_SECRET
    value: ""
  - name: INVISIBLE_CAPTCHA_SECRET
    value: "pwd"
  - name: LEGIT_ADMIN_DOMAINS
    value: "gov.pf"
  - name: LOGRAGE_ENABLED
    value: "disabled"
  - name: LOGRAGE_SOURCE
    value: ""
  - name: MAILCATCHER_ENABLED
    value: "disabled"
  - name: MAILCATCHER_HOST
    value: ""
  - name: MAILCATCHER_PORT
    value: ""
  - name: MAILER_LOGO_SRC
    value: "header/logo-md-wide.png"
  - name: MAILJET_API_KEY
    value: ""
  - name: MAILJET_SECRET_KEY
    value: ""
  - name: MAILTRAP_ENABLED
    value: "disabled"
  - name: MAILTRAP_PASSWORD
    value: ""
  - name: MAILTRAP_USERNAME
    value: ""
  - name: MATOMO_ENABLED
    value: "disabled"
  - name: MATOMO_COOKIE_DOMAIN
    value: "*.mes-demarches.gov.pf"
  - name: MATOMO_DOMAIN
    value: "*.mes-demarches.gov.pf"
  - name: MATOMO_HOST
    value: "beta.mes-demarches.gov.pf"
  - name: MATOMO_ID
    value: "1"
  - name: MATOMO_IFRAME_URL
    value: ""
  - name: MICROSOFT_CLIENT_ID
    value: ""
  - name: MICROSOFT_CLIENT_SECRET
    value: ""
  - name: OTP_SECRET_KEY
    value: "" 
  - name: PATH
    value: "${PATH}:${APP_PATH}/.bun/bin"
  - name: PIPEDRIVE_KEY
    value: ""
  - name: PROCEDURE_DEFAULT_LOGO_SRC
    value: "polynesie.png"
  - name: RAILS_ENV
    value: "production"
  - name: RAILS_LOG_TO_STDOUT
    value: ""
  - name: RAILS_SERVE_STATIC_FILES
    value: true
  - name: RUBY_YJIT_ENABLE
    value: true
  - name: SAML_IDP_ENABLED
    value: ""
  - name: SAML_IDP_CERTIFICATE
    value: "billybop"
  - name: SAML_IDP_SECRET_KEY
    value: "-----BEGIN RSA PRIVATE KEY-----
  - name: blabla+blabla
  - name: -----END RSA PRIVATE KEY-----"
  - name: SECRET_KEY_BASE
    value: "05a2d479d8e412198dabd08ef0eee9d6e180f5cbb48661a35fd1cae287f0a93d40b5f1da08f06780d698bbd458a0ea97f730f83ee780de5d4e31f649a0130cf0"
  - name: S3_ENDPOINT
    value: "" 
  - name: S3_BUCKET
    value: "" 
  - name: S3_ACCESS_KEY
    value: "" 
  - name: S3_SECRET_KEY
    value: "" 
  - name: S3_REGION
    value: "" 
  - name: SENDINBLUE_API_V3_KEY
    value: ""
  - name: SENDINBLUE_BALANCING_VALUE
    value: "100"
  - name: SENDINBLUE_CLIENT_KEY
    value: ""
  - name: SENDINBLUE_LOGIN_URL
    value: ""
  - name: SENDINBLUE_SMTP_KEY
    value: ""
  - name: SENDINBLUE_USER_NAME
    value: ""
  - name: SENTRY_CURRENT_ENV
    value: ""
  - name: SENTRY_DSN_JS
    value: ""
  - name: SENTRY_DSN_RAILS
    value: ""
  - name: SENTRY_ENABLED
    value: "disabled"
  - name: SIGNING_KEY
    value: "aef3153a9829fa4ba10acb02927ac855df6b92795b1ad265d654443c4b14a017"
  - name: SIPF_CLIENT_BASE_URL
    value: ""
  - name: SIPF_CLIENT_ID
    value: ""
  - name: SIPF_CLIENT_SECRET
    value: ""
  - name: SKYLIGHT_AUTHENTICATION_KEY
    value: ""
  - name: SKYLIGHT_DISABLE_AGENT
    value: "true"
  - name: SOURCE
    value: "tps_local"
  - name: STRICT_EMAIL_VALIDATION_STARTS_ON
    value: "2024-04-24"
  - name: TATOU_BASE_URL
    value: ""
  - name: TATOU_CLIENT_ID
    value: ""
  - name: TATOU_CLIENT_SECRET
    value: ""
  - name: TRUSTED_NETWORKS
    value: ""
  - name: CERTIGNA_USERPWD
    value: ""
  - name: WATERMARK_FILE
    value: "watermark_pf.png"
  - name: WEASYPRINT_URL
    value: "http://weasyprint:5000/pdf"
  - name: YAHOO_CLIENT_ID
    value: ""
  - name: YAHOO_CLIENT_SECRET
    value: ""
# Si tu as besoin de secrets (ex. JWT, DB password) :
secret:
  enabled: true
  name: demarche-numerique-secret
  # les valeurs seront injectées via `kubectl create secret` ou via OpenShift UI
...
