---
# SPDX-License-Identifier: AGPL-3.0-or-later
apiVersion: v2
name: kanban
version: 0.0.1 # version du chart (à incrémenter)
description: A Helm chart for deploying a kanban following frecnh government design state on an OpenShift like Kubernetes cluster
type: application
license: "AGPL-3.0"
keywords:
  - kanban
  - DSFR
  - openshift
  - helm
home: https://github.com/hnoel/kanban
sources:
  - https://github.com/hnoel/kanban
maintainers:
  - name: henri NOËL
    email: hnoel@users.noreply.github.com
icon: https://cdn.jsdelivr.net/npm/@gouvfr/dsfr@1.14.4/dist/favicon/favicon.svg
appVersion: "2026-05-05-01"
deprecated: false
...
