---
replicaCount: 2

image:
  repository: ghcr.io/hnoel/kanban
  tag: "main"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  extHttpPort: 80
  intHttpPort: 8080
  extHttpsPort: 443
  intHttpsPort: 8443

route:
  enabled: true
  host: example.com # à surcharger en prod
  tls: true

resources:
  limits:
    cpu: "2"
    memory: "2Gi"
  requests:
    cpu: "1"
    memory: "1Gi"

env:
  - name: queue_port
    value: 8443
  - name: user_port
    value: 8080
...
