---
name: scan with KICS and upload SARIF

# Configures this workflow to run manually or every time a change is pushed to the branch called `master`.
on:
  workflow_dispatch: {}
  push:
    branches: ['main']
  #pull_request:
  #  branches: [main]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    name: kics-action
    steps:
      - name: 'Checkout repo "https://github.com/demarche-numerique/demarche.numerique.gouv.fr"'
        uses: actions/checkout@v6
        with:
          repository: 'demarche-numerique/demarche.numerique.gouv.fr'
      - name: 'Checkout repo "https://github.com/hnoel/demarche.numerique.gouv.fr" into "./hnoel"'
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          path: './hnoel'
      - name: Merge checkout repositories
        run: |
          cp -r ./hnoel/* . && 
          rm -rf ./.git &&
          mv ./hnoel/.git . && 
          rm -rf ./hnoel
        shell: bash
      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@v2.1.19
        with:
          path: ./
          # when provided with a directory on output_path
          # it will generate the specified reports file named 'results.{extension}'
          # in this example it will generate:
          # - results-dir/results.json
          # - results-dir/results.sarif
          ignore_on_exit: results
          output_path: results-dir
          enable_comments: true
          output_formats: 'sarif'
      - name: Upload Kics results
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: results-dir/results.sarif
      # - name: Upload SARIF file (require paid subscription)
      #   uses: github/codeql-action/upload-sarif@v4
      #   with:
      #     # Path to SARIF file relative to the root of the repository
      #     sarif_file: results-dir/results.sarif
      #     # Optional category for the results
      #     # Used to differentiate multiple results for one commit
      #     category: kics-scanner
      # - name: set up repository for Docker compose linter
      #   run: cd hnoel
      #   shell: bash
      # - name: dclint
      #   uses: docker-compose-linter/dclint-github-action/reviewdog-action@v1.6.0
      #   with:
      #     reporter: github-pr-review # Default is `github-pr-check`
      #     dclint_flags: ./ # Default is `.`
      # - uses: docker-compose-linter/dclint-github-action@v1.6.0
      #   with:
      #     path: ./
      #     recursive: true
...
